name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Version Number'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Release Branch
        run: git checkout -b release/${{ github.event.inputs.versionName }}

      - name: Initialize mandatory git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email noreply@github.com

      - name: Install poetry
        run: pip install poetry

      - name: Update Package Version
        run: poetry version ${{ github.event.inputs.versionName }}

      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
        version: ${{ github.event.inputs.versionName }}

      - name: Commit Changes
        id: make-commit
        run: |
            git add pyproject.toml
            git add CHANGELOG.md
            git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
            echo "::set-output name=commit::$(git rev-parse HEAD)"

      - name: Push Release Branch
        run: git push origin release/${{ github.event.inputs.versionName }}
